// Copyright (c) Microsoft Corporation.
// All rights reserved.
//
// This code is licensed under the MIT License.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files(the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and / or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions :
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.

using Microsoft.Management.Services.Api;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Linq;
using System.Threading.Tasks;

namespace Microsoft.Intune
{
    /// <summary>
    /// API to download CARequests that were generated by Intune
    /// </summary>
    public class IntuneCARequestClient
    {
        public const string DEFAULT_SERVICE_VERSION = "2018-02-20";
        public const string CAREQUEST_SERVICE_NAME = "StatelessPkiConnectorService";
        public const string DOWNLOADCAREQUESTS_URL = "CertificateAuthorityRequests/downloadCARequests";
        public const string UPLOADCAREQUESTRESULTS_URL = "CertificateAuthorityRequests/uploadCARequestResults";
        public const int MAXREQUESTS_MAXVALUE = 500;

        private TraceSource trace = new TraceSource(nameof(IntuneCARequestClient));

        /// <summary>
        /// The version of the ScepRequestValidationFEService that we are making requests against.
        /// </summary>
        private string serviceVersion = null;

        /// <summary>
        /// The CertificateAuthority Identifier to be used in log correlation on Intune.
        /// </summary>
        private string providerNameAndVersion = null;

        /// <summary>
        /// The Intune client to use to make requests to Intune services.
        /// </summary>
        private IIntuneClient intuneClient = null;

        /// <summary>
        /// Creates an new instance of IntuneCARequestClient
        /// </summary>
        /// <param name="configProperties">Config dictionary containing properties for the client.</param>
        /// <param name="trace">Trace</param>
        /// <param name="intuneClient">IntuneClient to use to make requests to intune.</param>
        [SuppressMessage("Microsoft.Usage", "CA2208", Justification = "Using a parameter coming from an object.")]
        public IntuneCARequestClient(
            Dictionary<string,string> configProperties,
            TraceSource trace = null,
            IIntuneClient intuneClient = null)
        {
            // Required Parameters
            if (configProperties == null)
            {
                throw new ArgumentNullException(nameof(configProperties));
            }

            configProperties.TryGetValue("PROVIDER_NAME_AND_VERSION", out this.providerNameAndVersion);
            if (string.IsNullOrWhiteSpace(providerNameAndVersion))
            {
                throw new ArgumentNullException(nameof(providerNameAndVersion));
            }

            // Optional Parameters
            if (trace != null)
            {
                this.trace = trace;
            }

            configProperties.TryGetValue("StatelessPkiConnectorServiceVersion", out this.serviceVersion);
            serviceVersion = serviceVersion ?? DEFAULT_SERVICE_VERSION;

            // Dependencies
            var adalClient = new AdalClient(
                        // Required
                        configProperties,
                        // Overrides
                        trace: trace
                        );

            this.intuneClient = intuneClient ?? new IntuneClient(
                    // Required    
                    configProperties,
                    // Overrides
                    trace: trace,
                    // Dependencies
                    adalClient: adalClient,
                    locationProvider: new IntuneServiceLocationProvider(
                        // Required
                        configProperties,
                        // Overrides
                        trace: trace,
                        // Dependencies
                        authClient: adalClient
                        )
                    );
        }

        /// <summary>
        /// Downloads a list of CARequests from Intune to be acted on
        /// </summary>
        /// <param name="transactionId"></param>
        /// <param name="maxCARequestsToDownload"></param>
        /// <param name="caRequestType"></param>
        /// <param name="certificateProviderName"></param>
        /// <param name="issuerName"></param>
        /// <returns>List of CARequests</returns>
        public async Task<List<CARequest>> DownloadCARequestsAsync(string transactionId, int maxCARequestsToDownload, CARequestType? caRequestType = null, string certificateProviderName = null, string issuerName = null)
        {
            if (string.IsNullOrWhiteSpace(transactionId))
            {
                throw new ArgumentNullException(nameof(transactionId));
            }

            if (maxCARequestsToDownload <= 0 || maxCARequestsToDownload > MAXREQUESTS_MAXVALUE)
            {
                throw new ArgumentOutOfRangeException($"{nameof(maxCARequestsToDownload)} should be between 1 and {MAXREQUESTS_MAXVALUE}. {nameof(maxCARequestsToDownload)} value Requested: {maxCARequestsToDownload}."););
            }

            var downloadParamsObj = new CARequestDownloadParameters()
            {
                MaxMessages = maxCARequestsToDownload,
                CertificateProviderName = certificateProviderName, 
                IssuerName = issuerName,
                RequestType = caRequestType,
            };

            JObject requestBody = new JObject(new JProperty("downloadParameters", downloadParamsObj));

            string result = await PostAsync(requestBody, DOWNLOADCAREQUESTS_URL, transactionId);

            List<CARequest> requests = JsonConvert.DeserializeObject<IEnumerable<CARequest>>(result).ToList();

            return requests;
        }

        /// <summary>
        /// Send a list of CARequest results to Intune
        /// </summary>
        /// <param name="transactionId">The transactionId of the CSR</param>
        /// <param name="requestResults">List of CARequestResults to send to Intune</param>
        public async Task UploadCARequestResults(string transactionId, List<CARequestResult> requestResults)
        {
            if (string.IsNullOrWhiteSpace(transactionId))
            {
                throw new ArgumentNullException(nameof(transactionId));
            }

            if (requestResults == null || requestResults.Count == 0)
            {
                throw new ArgumentNullException(nameof(requestResults));
            }

            JObject requestBody = new JObject(new JProperty("results", requestResults));

            string result = await PostAsync(requestBody, UPLOADCAREQUESTRESULTS_URL, transactionId);

            if (!bool.TryParse(result, out bool postSuccessful) || !postSuccessful)
            {
                throw new IntuneClientException($"Results not successfully recorded in Intune. Expected 'true' from service. Recieved: '{result}'");
            }
        }

        private async Task<string> PostAsync(JObject requestBody, string urlSuffix, string transactionId)
        {
            Guid activityId = Guid.NewGuid();
            string resultJson = await intuneClient.PostAsync(CAREQUEST_SERVICE_NAME,
                        urlSuffix,
                        serviceVersion,
                        requestBody,
                        activityId);
            trace.TraceEvent(TraceEventType.Information, 0, $"Activity {activityId} has completed.");
            trace.TraceEvent(TraceEventType.Information, 0, resultJson);

            return resultJson;
        }
    }
}